"""phase 1 refactor

Revision ID: 235ffe2efeb1
Revises: b9bd47af10cf
Create Date: 2026-04-04 10:15:58.524759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235ffe2efeb1'
down_revision = 'b9bd47af10cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('configuration_service_type',
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ),
    sa.PrimaryKeyConstraint('configuration_id', 'service_type_id')
    )
    op.drop_table('gtfs_calendar')
    op.drop_table('gtfs_rider_categories')
    op.drop_table('gtfs_fare_transfer_rules')
    op.drop_table('gtfs_feed_info')
    op.drop_table('gtfs_shapes')
    op.drop_table('gtfs_fare_media')
    op.drop_table('gtfs_stops')
    op.drop_table('gtfs_fare_products')
    op.drop_table('gtfs_trips')
    op.drop_table('gtfs_timeframes')
    op.drop_table('gtfs_agency')
    op.drop_table('gtfs_stop_times')
    op.drop_table('gtfs_calendar_dates')
    op.drop_table('gtfs_routes')
    op.drop_table('gtfs_fare_leg_rules')
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gtfs_feed_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('gtfs_feed_url')

    op.create_table('gtfs_fare_leg_rules',
    sa.Column('leg_group_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('network_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fare_product_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('from_timeframe_group_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('to_timeframe_group_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['fare_product_id'], ['gtfs_fare_products.fare_product_id'], ),
    sa.ForeignKeyConstraint(['from_timeframe_group_id'], ['gtfs_timeframes.timeframe_group_id'], name=op.f('fk_fare_leg_rules_from_timeframe')),
    sa.ForeignKeyConstraint(['to_timeframe_group_id'], ['gtfs_timeframes.timeframe_group_id'], name=op.f('fk_fare_leg_rules_to_timeframe')),
    sa.PrimaryKeyConstraint('leg_group_id', 'fare_product_id', 'from_timeframe_group_id')
    )
    op.create_table('gtfs_routes',
    sa.Column('route_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('agency_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('route_short_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('route_long_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('route_desc', sa.TEXT(), nullable=True),
    sa.Column('route_type', sa.INTEGER(), nullable=False),
    sa.Column('route_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('route_color', sa.VARCHAR(length=6), nullable=True),
    sa.Column('route_text_color', sa.VARCHAR(length=6), nullable=True),
    sa.Column('route_sort_order', sa.INTEGER(), nullable=True),
    sa.Column('network_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['gtfs_agency.agency_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('gtfs_calendar_dates',
    sa.Column('service_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('exception_type', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['gtfs_calendar.service_id'], ),
    sa.PrimaryKeyConstraint('service_id', 'date')
    )
    op.create_table('gtfs_stop_times',
    sa.Column('trip_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('arrival_time', sa.TIME(), nullable=False),
    sa.Column('departure_time', sa.TIME(), nullable=False),
    sa.Column('stop_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('stop_sequence', sa.INTEGER(), nullable=False),
    sa.Column('stop_headsign', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pickup_type', sa.INTEGER(), nullable=True),
    sa.Column('drop_off_type', sa.INTEGER(), nullable=True),
    sa.Column('shape_dist_traveled', sa.FLOAT(), nullable=True),
    sa.Column('timepoint', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['gtfs_stops.stop_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['gtfs_trips.trip_id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'stop_sequence')
    )
    op.create_table('gtfs_agency',
    sa.Column('agency_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('agency_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('agency_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('agency_timezone', sa.VARCHAR(length=50), nullable=False),
    sa.Column('agency_lang', sa.VARCHAR(length=10), nullable=True),
    sa.Column('agency_phone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('agency_fare_url', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('agency_id')
    )
    op.create_table('gtfs_timeframes',
    sa.Column('timeframe_group_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['gtfs_calendar.service_id'], ),
    sa.PrimaryKeyConstraint('timeframe_group_id', 'start_time', 'end_time')
    )
    op.create_table('gtfs_trips',
    sa.Column('trip_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('route_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('trip_headsign', sa.VARCHAR(length=255), nullable=True),
    sa.Column('trip_short_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('direction_id', sa.INTEGER(), nullable=True),
    sa.Column('block_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('shape_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('wheelchair_accessible', sa.INTEGER(), nullable=True),
    sa.Column('bikes_allowed', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['gtfs_routes.route_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['gtfs_calendar.service_id'], ),
    sa.ForeignKeyConstraint(['shape_id'], ['gtfs_shapes.shape_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('gtfs_fare_products',
    sa.Column('fare_product_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fare_product_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('rider_category_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('fare_media_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.ForeignKeyConstraint(['fare_media_id'], ['gtfs_fare_media.fare_media_id'], ),
    sa.ForeignKeyConstraint(['rider_category_id'], ['gtfs_rider_categories.rider_category_id'], ),
    sa.PrimaryKeyConstraint('fare_product_id')
    )
    op.create_table('gtfs_stops',
    sa.Column('stop_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('stop_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('stop_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('stop_desc', sa.TEXT(), nullable=True),
    sa.Column('stop_lat', sa.FLOAT(), nullable=False),
    sa.Column('stop_lon', sa.FLOAT(), nullable=False),
    sa.Column('zone_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('stop_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('location_type', sa.INTEGER(), nullable=True),
    sa.Column('parent_station', sa.VARCHAR(length=50), nullable=True),
    sa.Column('stop_timezone', sa.VARCHAR(length=50), nullable=True),
    sa.Column('wheelchair_boarding', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_station'], ['gtfs_stops.stop_id'], ),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_table('gtfs_fare_media',
    sa.Column('fare_media_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fare_media_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('fare_media_type', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('fare_media_id')
    )
    op.create_table('gtfs_shapes',
    sa.Column('shape_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('shape_pt_lat', sa.FLOAT(), nullable=False),
    sa.Column('shape_pt_lon', sa.FLOAT(), nullable=False),
    sa.Column('shape_pt_sequence', sa.INTEGER(), nullable=False),
    sa.Column('shape_dist_traveled', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('shape_id', 'shape_pt_lat', 'shape_pt_lon', 'shape_pt_sequence')
    )
    op.create_table('gtfs_feed_info',
    sa.Column('feed_publisher_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('feed_publisher_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('feed_lang', sa.VARCHAR(length=10), nullable=False),
    sa.Column('feed_start_date', sa.DATE(), nullable=True),
    sa.Column('feed_end_date', sa.DATE(), nullable=True),
    sa.Column('feed_version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('feed_contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('feed_contact_url', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('feed_publisher_name')
    )
    op.create_table('gtfs_fare_transfer_rules',
    sa.Column('from_leg_group_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('to_leg_group_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fare_product_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('transfer_count', sa.INTEGER(), nullable=True),
    sa.Column('duration_limit', sa.INTEGER(), nullable=True),
    sa.Column('duration_limit_type', sa.INTEGER(), nullable=True),
    sa.Column('fare_transfer_type', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['fare_product_id'], ['gtfs_fare_products.fare_product_id'], ),
    sa.PrimaryKeyConstraint('from_leg_group_id', 'to_leg_group_id')
    )
    op.create_table('gtfs_rider_categories',
    sa.Column('rider_category_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('rider_category_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_default_fare_category', sa.INTEGER(), nullable=True),
    sa.Column('min_age', sa.INTEGER(), nullable=True),
    sa.Column('max_age', sa.INTEGER(), nullable=True),
    sa.Column('eligibility_url', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('rider_category_id')
    )
    op.create_table('gtfs_calendar',
    sa.Column('service_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('monday', sa.INTEGER(), nullable=False),
    sa.Column('tuesday', sa.INTEGER(), nullable=False),
    sa.Column('wednesday', sa.INTEGER(), nullable=False),
    sa.Column('thursday', sa.INTEGER(), nullable=False),
    sa.Column('friday', sa.INTEGER(), nullable=False),
    sa.Column('saturday', sa.INTEGER(), nullable=False),
    sa.Column('sunday', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.drop_table('configuration_service_type')
    op.drop_table('service_types')
    # ### end Alembic commands ###
