"""Add AFI history and parent_afi_id

Revision ID: 2861372f003b
Revises: 7ca55cdcceb9
Create Date: 2025-08-24 17:53:07.692584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2861372f003b'
down_revision = '7ca55cdcceb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_function_implementation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('afi_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['afi_id'], ['agency_function_implementations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agency_function_implementation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agency_function_implementation_history_afi_id'), ['afi_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agency_function_implementation_history_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('agency_function_implementations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_afi_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_afi_parent_afi',  # name is required in batch mode
            'agency_function_implementations',
            ['parent_afi_id'], ['id'],
            ondelete='SET NULL'
        )
        batch_op.create_index('ix_afi_parent_afi_id', ['parent_afi_id'], unique=False)
        batch_op.create_index('idx_afi_agency_function', ['agency_id', 'function_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_function_implementations', schema=None) as batch_op:
        batch_op.drop_index('idx_afi_agency_function')
        batch_op.drop_index('ix_afi_parent_afi_id')
        batch_op.drop_constraint('fk_afi_parent_afi', type_='foreignkey')
        batch_op.drop_column('parent_afi_id')

    with op.batch_alter_table('agency_function_implementation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agency_function_implementation_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_agency_function_implementation_history_afi_id'))

    op.drop_table('agency_function_implementation_history')
    # ### end Alembic commands ###
