"""add gtfs fixes

Revision ID: 344407203160
Revises: 8b01597924cb
Create Date: 2025-07-19 16:42:34.261299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344407203160'
down_revision = '8b01597924cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gtfs_fare_leg_rules', schema=None) as batch_op:
        batch_op.alter_column('from_timeframe_group_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gtfs_fare_leg_rules', schema=None) as batch_op:
        batch_op.alter_column('from_timeframe_group_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
