"""Initial Component Refactor

Revision ID: 5e5735f28b17
Revises: 
Create Date: 2025-05-28 21:17:53.699441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5735f28b17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('ceo', sa.String(length=128), nullable=True),
    sa.Column('address_hq', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('transit_map_link', sa.String(length=256), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_transit_system_name')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functional_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('standard_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('vendor_email', sa.String(length=255), nullable=True),
    sa.Column('vendor_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_vendor_name')
    )
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('deployment_date', sa.Date(), nullable=True),
    sa.Column('update_frequency', sa.String(length=50), nullable=True),
    sa.Column('known_issues', sa.String(length=500), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('parent_component_id', sa.Integer(), nullable=True),
    sa.Column('is_composite', sa.Boolean(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('criticality', sa.Enum('high', 'medium', 'low', name='criticality'), nullable=False),
    sa.Column('functional_area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['functional_area_id'], ['functional_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_standard',
    sa.Column('integration_point_id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('integration_point_id', 'standard_id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('tag_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_group_id'], ['tag_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('component_integration',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('integration_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.PrimaryKeyConstraint('component_id', 'integration_point_id')
    )
    op.create_table('component_tag',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('component_id', 'tag_id')
    )
    op.create_table('function_component',
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('function_id', 'component_id')
    )
    op.create_table('integration_tag',
    sa.Column('integration_point_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('integration_point_id', 'tag_id')
    )
    op.create_table('update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('change_summary', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('update_logs')
    op.drop_table('integration_tag')
    op.drop_table('function_component')
    op.drop_table('component_tag')
    op.drop_table('component_integration')
    op.drop_table('tags')
    op.drop_table('integration_standard')
    op.drop_table('functions')
    op.drop_table('components')
    op.drop_table('vendors')
    op.drop_table('tag_groups')
    op.drop_table('standards')
    op.drop_table('integration_points')
    op.drop_table('functional_areas')
    op.drop_table('examples')
    op.drop_table('agencies')
    # ### end Alembic commands ###
