"""add new tables for config refactor

Revision ID: 62d165f8257e
Revises: fa5f6f3f2737
Create Date: 2025-09-07 09:18:14.843687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d165f8257e'
down_revision = 'fa5f6f3f2737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('parent_product_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle_stage', sa.Enum('planned', 'pilot', 'production', 'deprecated', 'retired', name='lifecyclestage'), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_parent_product_id'), ['parent_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deployment_date', sa.Date(), nullable=True),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('implementation_notes', sa.String(length=1000), nullable=True),
    sa.Column('security_review_date', sa.Date(), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'function_id', 'component_id', name='uq_configuration_agency_function_component')
    )
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.create_index('ix_configuration_agency_function', ['agency_id', 'function_id'], unique=False)
        batch_op.create_index('ix_configuration_component', ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_function_id'), ['function_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configurations_status'), ['status'], unique=False)

    op.create_table('product_integration',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('integration_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integration_point_id'], ['integration_points.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'integration_point_id')
    )
    op.create_table('product_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('support_end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'version', name='uq_product_version')
    )
    with op.batch_alter_table('product_versions', schema=None) as batch_op:
        batch_op.create_index('ix_product_version_product_id_version', ['product_id', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_versions_product_id'), ['product_id'], unique=False)

    op.create_table('configuration_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuration_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_history_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_history_timestamp'), ['timestamp'], unique=False)

    op.create_table('configuration_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('configuration_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deployment_date', sa.Date(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['configurations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuration_id', 'product_id', name='uq_configuration_product')
    )
    with op.batch_alter_table('configuration_products', schema=None) as batch_op:
        batch_op.create_index('ix_configuration_product_product_version', ['product_id', 'product_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_products_configuration_id'), ['configuration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_products_product_version_id'), ['product_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_configuration_products_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_products_status'))
        batch_op.drop_index(batch_op.f('ix_configuration_products_product_version_id'))
        batch_op.drop_index(batch_op.f('ix_configuration_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_configuration_products_configuration_id'))
        batch_op.drop_index('ix_configuration_product_product_version')

    op.drop_table('configuration_products')
    with op.batch_alter_table('configuration_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_configuration_history_configuration_id'))

    op.drop_table('configuration_history')
    with op.batch_alter_table('product_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_versions_product_id'))
        batch_op.drop_index('ix_product_version_product_id_version')

    op.drop_table('product_versions')
    op.drop_table('product_integration')
    with op.batch_alter_table('configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configurations_status'))
        batch_op.drop_index(batch_op.f('ix_configurations_function_id'))
        batch_op.drop_index(batch_op.f('ix_configurations_component_id'))
        batch_op.drop_index(batch_op.f('ix_configurations_agency_id'))
        batch_op.drop_index('ix_configuration_component')
        batch_op.drop_index('ix_configuration_agency_function')

    op.drop_table('configurations')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_products_parent_product_id'))

    op.drop_table('products')
    # ### end Alembic commands ###
