"""Add Suggestion model

Revision ID: 77db9f12df99
Revises: 235ffe2efeb1
Create Date: 2026-04-08 20:20:01.080227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77db9f12df99'
down_revision = '235ffe2efeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('suggested_value', sa.Text(), nullable=True),
    sa.Column('current_value', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index('ix_suggestion_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_suggestion_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_suggestions_entity_type'))
        batch_op.drop_index(batch_op.f('ix_suggestions_entity_id'))
        batch_op.drop_index('ix_suggestion_status_created')
        batch_op.drop_index('ix_suggestion_entity')

    op.drop_table('suggestions')
    # ### end Alembic commands ###
