"""add email_domain

Revision ID: 7ca55cdcceb9
Revises: 5799d8c821a9
Create Date: 2025-08-22 22:20:20.962104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca55cdcceb9'
down_revision = '5799d8c821a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_domain', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('email_domain')

    # ### end Alembic commands ###
