"""remove contact_ fields from vendor

Revision ID: 8b00e14cf89d
Revises: 1b412d7114be
Create Date: 2025-05-30 08:55:10.126024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b00e14cf89d'
down_revision = '1b412d7114be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(length=50), nullable=True))
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_name')
        batch_op.drop_column('contact_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
