"""Add agency function implementation tracking

Revision ID: af19d4b4d2a5
Revises: 5e5735f28b17
Create Date: 2025-05-29 12:41:32.450237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af19d4b4d2a5'
down_revision = '5e5735f28b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_function_implementations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('deployment_date', sa.Date(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('deployment_notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('implementation_notes', sa.String(length=1000), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'function_id', 'component_id', name='uq_agency_function_component')
    )
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_transit_system_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transit_system_name', type_='unique')

    op.drop_table('agency_function_implementations')
    # ### end Alembic commands ###
