"""add short_description to component

Revision ID: b5a9767ca0f7
Revises: b61cee965b56
Create Date: 2025-09-12 20:44:48.940278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a9767ca0f7'
down_revision = 'b61cee965b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###
