"""remove afi

Revision ID: b61cee965b56
Revises: c35343114d05
Create Date: 2025-09-07 17:34:36.543067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b61cee965b56'
down_revision = 'c35343114d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_function_implementations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_afi_agency_function'))
        batch_op.drop_index(batch_op.f('ix_afi_parent_afi_id'))

    op.drop_table('agency_function_implementations')
    with op.batch_alter_table('agency_function_implementation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agency_function_implementation_history_afi_id'))
        batch_op.drop_index(batch_op.f('ix_agency_function_implementation_history_timestamp'))

    op.drop_table('agency_function_implementation_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency_function_implementation_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('afi_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('changed_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('old_values', sqlite.JSON(), nullable=True),
    sa.Column('new_values', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['afi_id'], ['agency_function_implementations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agency_function_implementation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agency_function_implementation_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_agency_function_implementation_history_afi_id'), ['afi_id'], unique=False)

    op.create_table('agency_function_implementations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agency_id', sa.INTEGER(), nullable=False),
    sa.Column('function_id', sa.INTEGER(), nullable=False),
    sa.Column('component_id', sa.INTEGER(), nullable=False),
    sa.Column('deployment_date', sa.DATE(), nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('deployment_notes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('implementation_notes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('additional_metadata', sqlite.JSON(), nullable=True),
    sa.Column('parent_afi_id', sa.INTEGER(), nullable=True),
    sa.Column('security_review_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.ForeignKeyConstraint(['parent_afi_id'], ['agency_function_implementations.id'], name=op.f('fk_afi_parent_afi'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'function_id', 'component_id', name=op.f('uq_agency_function_component'))
    )
    with op.batch_alter_table('agency_function_implementations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_afi_parent_afi_id'), ['parent_afi_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_afi_agency_function'), ['agency_id', 'function_id'], unique=False)

    # ### end Alembic commands ###
