"""add user

Revision ID: b9bd47af10cf
Revises: b5a9767ca0f7
Create Date: 2026-01-19 17:47:02.824279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bd47af10cf'
down_revision = 'b5a9767ca0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'sub', name='uq_user_provider_sub')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_user_provider_sub', ['provider', 'sub'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('verified_agency_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verified_agency_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verified_agency_domains_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verified_agency_domains_domain'), ['domain'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verified_agency_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verified_agency_domains_domain'))
        batch_op.drop_index(batch_op.f('ix_verified_agency_domains_agency_id'))

    op.drop_table('verified_agency_domains')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_agency_id'))
        batch_op.drop_index('ix_user_provider_sub')

    op.drop_table('users')
    # ### end Alembic commands ###
