"""add component lifecycle/eol and AFI security review date

Revision ID: fa5f6f3f2737
Revises: f5a847bc4d52
Create Date: 2025-09-06 18:04:01.573578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'fa5f6f3f2737'
down_revision = 'f5a847bc4d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_agency_function_implementations')
    with op.batch_alter_table('agency_function_implementation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_afi_history_afi_id'))
        batch_op.drop_index(batch_op.f('ix_afi_history_timestamp'))

    with op.batch_alter_table('agency_function_implementations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_review_date', sa.Date(), nullable=True))

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lifecycle_stage', sa.Enum('planned', 'pilot', 'production', 'deprecated', 'retired', name='lifecyclestage'), nullable=True))
        batch_op.add_column(sa.Column('support_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_column('support_end_date')
        batch_op.drop_column('lifecycle_stage')

    with op.batch_alter_table('agency_function_implementations', schema=None) as batch_op:
        batch_op.drop_column('security_review_date')

    with op.batch_alter_table('agency_function_implementation_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_afi_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_afi_history_afi_id'), ['afi_id'], unique=False)

    op.create_table('_alembic_tmp_agency_function_implementations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agency_id', sa.INTEGER(), nullable=False),
    sa.Column('function_id', sa.INTEGER(), nullable=False),
    sa.Column('component_id', sa.INTEGER(), nullable=False),
    sa.Column('deployment_date', sa.DATE(), nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('deployment_notes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('implementation_notes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('additional_metadata', sqlite.JSON(), nullable=True),
    sa.Column('parent_afi_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['function_id'], ['functions.id'], ),
    sa.ForeignKeyConstraint(['parent_afi_id'], ['agency_function_implementations.id'], name=op.f('fk_afi_parent_afi'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'function_id', 'component_id', name=op.f('uq_agency_function_component'))
    )
    # ### end Alembic commands ###
